In [1]:
## Dataset Overview
The assignment uses banking industry data with 10 rows × 5 columns:
- **Customer_ID**: Unique identifier for each customer
- **Account_Balance**: Customer's account balance in dollars
- **Credit_Score**: Customer's credit score (300-900 range)
- **Transaction_Count**: Number of transactions in the last month
- **Years_Active**: Number of years the customer has been with the bank


SyntaxError: invalid character '×' (U+00D7) (3681616340.py, line 2)

In [ ]:
import numpy as np
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [ ]:
### Question 1: Array Creation and Manipulation

**Q1.1:** Create a 4x4 identity matrix using `np.eye()`

**Q1.2:** Create an array of 8 zeros using `np.zeros()`

**Q1.3:** Create an array of 6 ones using `np.ones()`

**Q1.4:** Create an array with values from 0 to 15 using `np.arange()`

**Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`

In [ ]:
# **Q1.1:** Create a 4x4 identity matrix using `np.eye()`
import numpy as np
np.eye(4)



array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#**Q1.2:** Create an array of 8 zeros using `np.zeros()`
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# **Q1.3:** Create an array of 6 ones using `np.ones()`
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [ ]:
# **Q1.4:** Create an array with values from 0 to 15 using `np.arange()`
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# **Q1.5:** Create an array with 8 evenly spaced values from 0 to 100 using `np.linspace()`
np.linspace(0,100,8)

array([  0.        ,  14.28571429,  28.57142857,  42.85714286,
        57.14285714,  71.42857143,  85.71428571, 100.        ])

In [ ]:
### Question 2: Array Attributes and Information

**Q2.1:** What is the shape of the `banking_data` array?

**Q2.2:** What is the data type of the `banking_data` array?

**Q2.3:** What is the size (total number of elements) of the `banking_data` array?

**Q2.4:** What is the number of dimensions of the `banking_data` array?

**Q2.5:** What is the memory size of the `banking_data` array in bytes?

In [ ]:
# **Q2.1:** What is the shape of the `banking_data` array?
import numpy as np
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)
print("Shape :",np.shape(banking_data))

[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]
Shape : (10, 5)


In [ ]:
# **Q2.2:** What is the data type of the `banking_data` array?
banking_data.dtype

dtype('int64')

In [ ]:
# **Q2.3:** What is the size (total number of elements) of the `banking_data` array?
banking_data.size 

50

In [ ]:
# **Q2.4:** What is the number of dimensions of the `banking_data` array?
banking_data.ndim

2

In [ ]:
# **Q2.5:** What is the memory size of the `banking_data` array in bytes?
banking_data.nbytes

400

In [ ]:
### Question 3: Indexing and Slicing

**Q3.1:** Extract the first row of `banking_data`

**Q3.2:** Extract the last row of `banking_data`

**Q3.3:** Extract the Account_Balance column (column index 1)

**Q3.4:** Extract the first 4 rows and first 3 columns

**Q3.5:** Extract rows 3 to 7 (inclusive)

In [ ]:
# **Q3.1:** Extract the first row of `banking_data`
banking_data[0]

array([   1, 5200,  720,   15,    2])

In [ ]:
# **Q3.2:** Extract the last row of `banking_data`
banking_data[9]

array([  10, 6700,  675,   22,    4])

In [ ]:
# **Q3.3:** Extract the Account_Balance column (column index 1)
print(banking_data)
banking_data[0:,1]

[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


array([ 5200, 15000,   300,  8700,  4300, 12000,   760, 22000,  9000,
        6700])

In [ ]:
# **Q3.4:** Extract the first 4 rows and first 3 columns
banking_data[0:4,0:3]

array([[    1,  5200,   720],
       [    2, 15000,   650],
       [    3,   300,   500],
       [    4,  8700,   810]])

In [ ]:
#**Q3.5:** Extract rows 3 to 7 (inclusive)
banking_data[2:7,0:]

array([[    3,   300,   500,     5,     1],
       [    4,  8700,   810,    30,     6],
       [    5,  4300,   690,    18,     3],
       [    6, 12000,   745,    55,    10],
       [    7,   760,   600,     8,     1]])

In [ ]:
## Question 4: Mathematical Operations

**Q4.1:** Calculate the sum of all account balances

**Q4.2:** Calculate the mean account balance

**Q4.3:** Calculate the standard deviation of account balances

**Q4.4:** Calculate the variance of account balances

**Q4.5:** Calculate the median account balance

In [ ]:
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
banking_data

array([[    1,  5200,   720,    15,     2],
       [    2, 15000,   650,    42,     8],
       [    3,   300,   500,     5,     1],
       [    4,  8700,   810,    30,     6],
       [    5,  4300,   690,    18,     3],
       [    6, 12000,   745,    55,    10],
       [    7,   760,   600,     8,     1],
       [    8, 22000,   860,    70,    12],
       [    9,  9000,   700,    17,     5],
       [   10,  6700,   675,    22,     4]])

In [ ]:
# **Q4.1:** Calculate the sum of all account balances
banking_data[0:,1].sum()

np.int64(83960)

In [ ]:
# **Q4.2:** Calculate the mean account balance
banking_data[0:,1].mean()

np.float64(8396.0)

In [ ]:
# **Q4.3:** Calculate the standard deviation of account balances
banking_data[0:,1].std()

np.float64(6291.656697563846)

In [ ]:
# **Q4.4:** Calculate the variance of account balances
banking_data[0:,1].var()

np.float64(39584944.0)

In [ ]:
#**Q4.5:** Calculate the median account balance
np.median(banking_data[0:,1])

np.float64(7700.0)

In [ ]:
### Question 5: Statistical Functions

**Q5.1:** Find the minimum and maximum account balances

**Q5.2:** Find the minimum and maximum credit scores

**Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)

**Q5.4:** Calculate the correlation between account balance and credit score

**Q5.5:** Calculate the covariance between account balance and credit score


In [ ]:
# **Q5.1:** Find the minimum and maximum account balances
print("minimum :",banking_data[0:,1].min())
print("maximum :",banking_data[0:,1].max())

minimum : 300
maximum : 22000


In [ ]:
# **Q5.2:** Find the minimum and maximum credit scores
print("minimum :",banking_data[0:,2].min())
print("maximum :",banking_data[0:,2].max())

minimum : 500
maximum : 860


In [ ]:
# **Q5.3:** Calculate the percentile values for account balances (25th, 50th, 75th)
print("Q25 :",np.quantile(banking_data[0:,1],0.25))
print("Q50 :",np.quantile(banking_data[0:,1],0.50))
print("Q75 :",np.quantile(banking_data[0:,1],0.75))

Q25 : 4525.0
Q50 : 7700.0
Q75 : 11250.0


In [ ]:
# **Q5.4:** Calculate the correlation between account balance and credit score
np.corrcoef(banking_data[0:,1],banking_data[0:,2])

array([[1.        , 0.73208837],
       [0.73208837, 1.        ]])

In [ ]:
#**Q5.5:** Calculate the covariance between account balance and credit score
np.cov(banking_data[0:,1],banking_data[0:,2])

array([[4.39832711e+07, 4.93811111e+05],
       [4.93811111e+05, 1.03444444e+04]])

In [ ]:
### Question 6: Array Reshaping and Manipulation

**Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns

**Q6.2:** Flatten the `banking_data` to a 1D array

**Q6.3:** Transpose the `banking_data`

**Q6.4:** Split the `banking_data` into 2 equal parts vertically

**Q6.5:** Split the `banking_data` into 2 equal parts horizontally

In [ ]:

banking_data

array([[    1,  5200,   720,    15,     2],
       [    2, 15000,   650,    42,     8],
       [    3,   300,   500,     5,     1],
       [    4,  8700,   810,    30,     6],
       [    5,  4300,   690,    18,     3],
       [    6, 12000,   745,    55,    10],
       [    7,   760,   600,     8,     1],
       [    8, 22000,   860,    70,    12],
       [    9,  9000,   700,    17,     5],
       [   10,  6700,   675,    22,     4]])

In [ ]:
# **Q6.1:** Reshape the `banking_data` to 5 rows × 10 columns
banking_data.reshape(5,10)

array([[    1,  5200,   720,    15,     2,     2, 15000,   650,    42,
            8],
       [    3,   300,   500,     5,     1,     4,  8700,   810,    30,
            6],
       [    5,  4300,   690,    18,     3,     6, 12000,   745,    55,
           10],
       [    7,   760,   600,     8,     1,     8, 22000,   860,    70,
           12],
       [    9,  9000,   700,    17,     5,    10,  6700,   675,    22,
            4]])

In [ ]:
#**Q6.2:** Flatten the `banking_data` to a 1D array
np.ravel(banking_data)

array([    1,  5200,   720,    15,     2,     2, 15000,   650,    42,
           8,     3,   300,   500,     5,     1,     4,  8700,   810,
          30,     6,     5,  4300,   690,    18,     3,     6, 12000,
         745,    55,    10,     7,   760,   600,     8,     1,     8,
       22000,   860,    70,    12,     9,  9000,   700,    17,     5,
          10,  6700,   675,    22,     4])

In [ ]:
# **Q6.3:** Transpose the `banking_data`
banking_data.T

array([[    1,     2,     3,     4,     5,     6,     7,     8,     9,
           10],
       [ 5200, 15000,   300,  8700,  4300, 12000,   760, 22000,  9000,
         6700],
       [  720,   650,   500,   810,   690,   745,   600,   860,   700,
          675],
       [   15,    42,     5,    30,    18,    55,     8,    70,    17,
           22],
       [    2,     8,     1,     6,     3,    10,     1,    12,     5,
            4]])

In [ ]:
# **Q6.4:** Split the `banking_data` into 2 equal parts vertically
np.vsplit(banking_data,2)

[array([[    1,  5200,   720,    15,     2],
        [    2, 15000,   650,    42,     8],
        [    3,   300,   500,     5,     1],
        [    4,  8700,   810,    30,     6],
        [    5,  4300,   690,    18,     3]]),
 array([[    6, 12000,   745,    55,    10],
        [    7,   760,   600,     8,     1],
        [    8, 22000,   860,    70,    12],
        [    9,  9000,   700,    17,     5],
        [   10,  6700,   675,    22,     4]])]

In [ ]:
# **Q6.5:** Split the `banking_data` into 2 equal parts horizontally
np.hsplit(banking_data,[2])

[array([[    1,  5200],
        [    2, 15000],
        [    3,   300],
        [    4,  8700],
        [    5,  4300],
        [    6, 12000],
        [    7,   760],
        [    8, 22000],
        [    9,  9000],
        [   10,  6700]]),
 array([[720,  15,   2],
        [650,  42,   8],
        [500,   5,   1],
        [810,  30,   6],
        [690,  18,   3],
        [745,  55,  10],
        [600,   8,   1],
        [860,  70,  12],
        [700,  17,   5],
        [675,  22,   4]])]

In [ ]:
### Question 7: Logical Operations and Filtering

**Q7.1:** Find customers with account balance greater than $100,000

**Q7.2:** Find customers with credit score greater than 800

**Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750

**Q7.4:** Count how many customers have account balance between $10,000 and $100,000

**Q7.5:** Find the index of the customer with the highest credit score

In [ ]:
# **Q7.1:** Find customers with account balance greater than $100,000(15000)
banking_data[banking_data[0:,1]>15000]

array([[    8, 22000,   860,    70,    12]])

In [ ]:
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
banking_data


array([[    1,  5200,   720,    15,     2],
       [    2, 15000,   650,    42,     8],
       [    3,   300,   500,     5,     1],
       [    4,  8700,   810,    30,     6],
       [    5,  4300,   690,    18,     3],
       [    6, 12000,   745,    55,    10],
       [    7,   760,   600,     8,     1],
       [    8, 22000,   860,    70,    12],
       [    9,  9000,   700,    17,     5],
       [   10,  6700,   675,    22,     4]])

In [ ]:
# **Q7.2:** Find customers with credit score greater than 800
banking_data[banking_data[0:,2]>800]      


array([[    4,  8700,   810,    30,     6],
       [    8, 22000,   860,    70,    12]])

In [ ]:
#**Q7.3:** Find customers with transaction count greater than 50 AND credit score less than 750
x=banking_data[(banking_data[0:,3]>50) & (banking_data[0:,3]<750)]  # for total count use banking_data[(banking_data[0:,3]>50) & (banking_data[0:,3]<750)].shape[0]


array([[    6, 12000,   745,    55,    10],
       [    8, 22000,   860,    70,    12]])

In [ ]:
# **Q7.4:** Count how many customers have account balance between $10,000 and $100,000 (10,000 and 20,000)
banking_data[(banking_data[0:,1]>=10000) & (banking_data[0:,1]<=20000)]

array([[    2, 15000,   650,    42,     8],
       [    6, 12000,   745,    55,    10]])

In [ ]:
# **Q7.5:** Find the index of the customer with the highest credit score
banking_data[0:,2].argmax()+1

np.int64(8)

In [ ]:
### Question 8: Sorting and Searching

**Q8.1:** Sort the `banking_data` by account balance (ascending)

**Q8.2:** Sort the `banking_data` by credit score (descending)

**Q8.3:** Find the indices that would sort the array by years active

**Q8.4:** Find the customer with the second highest account balance

**Q8.5:** Find the customer with the lowest transaction count

In [ ]:
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
banking_data


array([[    1,  5200,   720,    15,     2],
       [    2, 15000,   650,    42,     8],
       [    3,   300,   500,     5,     1],
       [    4,  8700,   810,    30,     6],
       [    5,  4300,   690,    18,     3],
       [    6, 12000,   745,    55,    10],
       [    7,   760,   600,     8,     1],
       [    8, 22000,   860,    70,    12],
       [    9,  9000,   700,    17,     5],
       [   10,  6700,   675,    22,     4]])

In [ ]:
#**Q8.1:** Sort the `banking_data` by account balance (ascending)
banking_data[banking_data[0:,1].argsort()]

array([[    3,   300,   500,     5,     1],
       [    7,   760,   600,     8,     1],
       [    5,  4300,   690,    18,     3],
       [    1,  5200,   720,    15,     2],
       [   10,  6700,   675,    22,     4],
       [    4,  8700,   810,    30,     6],
       [    9,  9000,   700,    17,     5],
       [    6, 12000,   745,    55,    10],
       [    2, 15000,   650,    42,     8],
       [    8, 22000,   860,    70,    12]])

In [ ]:
# **Q8.2:** Sort the `banking_data` by credit score (descending)
banking_data[banking_data[0:,2].argsort()[::-1]]   # for descending order use slicing [::-1]

array([[    8, 12000,   860,    70,    12],
       [    4,  5200,   810,    30,     6],
       [    6,  8700,   745,    55,    10],
       [    1,   300,   720,    15,     2],
       [    9, 15000,   700,    17,     5],
       [    5,  6700,   690,    18,     3],
       [   10, 22000,   675,    22,     4],
       [    2,   760,   650,    42,     8],
       [    7,  9000,   600,     8,     1],
       [    3,  4300,   500,     5,     1]])

In [ ]:
#**Q8.3:** Find the indices that would sort the array by years active
banking_data[banking_data[0:,4].argsort()]

array([[    1,   300,   720,    15,     1],
       [    2,   760,   650,    42,     1],
       [    3,  4300,   500,     5,     2],
       [    4,  5200,   810,    30,     3],
       [    5,  6700,   690,    18,     4],
       [    6,  8700,   745,    55,     5],
       [    7,  9000,   600,     8,     6],
       [    8, 12000,   860,    70,     8],
       [    9, 15000,   700,    17,    10],
       [   10, 22000,   675,    22,    12]])

In [ ]:
import numpy as np
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)


[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [ ]:
#**Q8.4:** Find the customer with the second highest account balance
sort=banking_data[0:,1].argsort()
second_highest = banking_data[sort[-2]]
second_highest
# -------------------or ---------------------
# h=banking_data[0:,1].max()
# print(h)
# sh=banking_data[(banking_data[0:,1]<h)]
# ssh=sh.max()
# second_highest=banking_data[banking_data[0:,1]==ssh]
# second_highest

array([    2, 15000,   650,    42,     8])

In [ ]:
#**Q8.5:** Find the customer with the lowest transaction count
banking_data[banking_data[:,3].argmin()]

array([  3, 300, 500,   5,   1])

In [ ]:
### Question 9: Mathematical Functions

**Q9.1:** Calculate the absolute values of all elements

**Q9.2:** Calculate the square root of all account balances

**Q9.3:** Calculate the square of all credit scores

**Q9.4:** Calculate the exponential of all transaction counts

**Q9.5:** Calculate the natural logarithm of all account balances

In [4]:
import numpy as np
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [5]:
# **Q9.1:** Calculate the absolute values of all elements
np.abs(banking_data)

array([[    1,  5200,   720,    15,     2],
       [    2, 15000,   650,    42,     8],
       [    3,   300,   500,     5,     1],
       [    4,  8700,   810,    30,     6],
       [    5,  4300,   690,    18,     3],
       [    6, 12000,   745,    55,    10],
       [    7,   760,   600,     8,     1],
       [    8, 22000,   860,    70,    12],
       [    9,  9000,   700,    17,     5],
       [   10,  6700,   675,    22,     4]])

In [6]:
# **Q9.2:** Calculate the square root of all account balances
np.sqrt(banking_data[0:,1])

array([ 72.11102551, 122.47448714,  17.32050808,  93.27379053,
        65.57438524, 109.5445115 ,  27.5680975 , 148.32396974,
        94.86832981,  81.85352772])

In [ ]:
# **Q9.3:** Calculate the square of all credit scores
#[Customer_ID,Account_Balance,Credit_Score,Transaction_Count,Years_active]
(banking_data[0:,2])**(2)


array([518400, 422500, 250000, 656100, 476100, 555025, 360000, 739600,
       490000, 455625])

In [7]:
# **Q9.4:** Calculate the exponential of all transaction counts
np.exp(banking_data[0:,3])

array([3.26901737e+06, 1.73927494e+18, 1.48413159e+02, 1.06864746e+13,
       6.56599691e+07, 7.69478527e+23, 2.98095799e+03, 2.51543867e+30,
       2.41549528e+07, 3.58491285e+09])

In [8]:
# **Q9.5:** Calculate the natural logarithm of all account balances
np.log(banking_data[0:,1])

array([8.5564139 , 9.61580548, 5.70378247, 9.0710783 , 8.3663703 ,
       9.39266193, 6.63331843, 9.99879773, 9.10497986, 8.80986281])

In [ ]:
### Question 10: Advanced Operations

**Q10.1:** Calculate the cumulative sum of account balances

**Q10.2:** Calculate the cumulative product of transaction counts

**Q10.3:** Calculate the difference between consecutive account balances

**Q10.4:** Calculate the gradient of account balances

**Q10.5:** Calculate the histogram of account balances with 5 bins

In [11]:
import numpy as np
print("[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]")
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]
[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [12]:
# **Q10.1:** Calculate the cumulative sum of account balances
# The cumulative sum means we keep adding values step by step. 
# Cumulative sum means you start with the first number, then keep adding the next numbers one by one., It shows how the total grows step by step.
np.cumsum(banking_data[0:,1])

array([ 5200, 20200, 20500, 29200, 33500, 45500, 46260, 68260, 77260,
       83960])

In [ ]:
#  **Q10.2:** Calculate the cumulative product of transaction counts
# Cumulative product means you start with the first number, then keep multiplying by the next numbers one by one.
np.cumprod(banking_data[0:,3])  

array([            15,            630,           3150,          94500,
              1701000,       93555000,      748440000,    52390800000,
         890643600000, 19594159200000])

In [ ]:
# **Q10.3:** Calculate the difference between consecutive account balances
np.diff(banking_data[0:,1])  

array([  9800, -14700,   8400,  -4400,   7700, -11240,  21240, -13000,
        -2300])

In [20]:
# **Q10.4:** Calculate the gradient of account balances
# It calculates the rate of change between consecutive elements of an array, This code computes the gradient (rate of change) of the Account_Balance column, assuming each customer ID is equally spaced by 1.
np.gradient(banking_data[0:,1],1)  #  gradident(f,dx) where f is input and dx is spacing between points (optional, default = 1))

array([ 9800., -2450., -3150.,  2000.,  1650., -1770.,  5000.,  4120.,
       -7650., -2300.])

In [24]:
# **Q10.5:** Calculate the histogram of account balances with 5 bins
# step 1:  Get the range of values --> find max and min values take then find range (range= max-min)
# step 2: Decide number of bins --> bin width =range/ no of bins
# step 3: Calculate bin edges --> bin edges= min_value + bin width , example : Bin 1: 300 → 300 + 4340 ≈ 4700 ,Bin 2: 4700 → 4700 + 4340 ≈ 9100  and so on.
# step 4: Count how many values fall in each bin ,example: Bin 1 (300–4700): 300, 4300, 760 → 3 customers ,Bin 2 (4700–9100): 5200, 8700 → 2 customers an so on.
print(np.histogram(banking_data[0:,1],bins=5))

(array([3, 3, 2, 1, 1]), array([  300.,  4640.,  8980., 13320., 17660., 22000.]))


In [ ]:
### Question 11: Random Numbers and Simulation

**Q11.1:** Generate 6 random integers between 1 and 1000

**Q11.2:** Generate 6 random floats between 0 and 1

**Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)

**Q11.4:** Shuffle the `banking_data` rows randomly

**Q11.5:** Set random seed to 123 and generate 4 random numbers

In [25]:
import numpy as np
print("[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]")
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]
[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [26]:
# **Q11.1:** Generate 6 random integers between 1 and 1000
np.random.randint(1,1000,6)

array([  2, 730, 993, 686, 286,  43], dtype=int32)

In [29]:
# **Q11.2:** Generate 6 random floats between 0 and 1
np.random.rand(6)

array([0.90774356, 0.68073135, 0.54516198, 0.66506821, 0.07165561,
       0.8978092 ])

In [ ]:
# **Q11.3:** Generate 6 random numbers from normal distribution (mean=700, std=100)
np.random.normal(700,100,6)  # np.random.normal()--->normal distribution

array([636.19031167, 688.6388222 , 901.70651726, 778.57942519,
       780.2583139 , 773.77398516])

In [ ]:
# **Q11.4:** Shuffle the `banking_data` rows randomly
np.random.shuffle(banking_data)  # it randomly shuffles each rows when you run code each time
banking_data


array([[    5,  4300,   690,    18,     3],
       [    8, 22000,   860,    70,    12],
       [    6, 12000,   745,    55,    10],
       [    2, 15000,   650,    42,     8],
       [    1,  5200,   720,    15,     2],
       [    7,   760,   600,     8,     1],
       [    4,  8700,   810,    30,     6],
       [    3,   300,   500,     5,     1],
       [   10,  6700,   675,    22,     4],
       [    9,  9000,   700,    17,     5]])

In [ ]:
# **Q11.5:** Set random seed to 123 and generate 4 random numbers
np.random.seed(123) # Seed: A value that initializes the random number generator to produce the same sequence of “random” numbers every time.
np.random.rand(4)

array([0.69646919, 0.28613933, 0.22685145, 0.55131477])

In [ ]:
### Question 12: Linear Algebra Operations

**Q12.1:** Calculate the dot product of account balance and credit score columns

**Q12.2:** Calculate the cross product of first two rows

**Q12.3:** Calculate the norm (magnitude) of the account balance column

**Q12.4:** Create a 3x3 matrix and calculate its determinant

**Q12.5:** Calculate the inverse of the 3x3 matrix

In [84]:
import numpy as np
print("[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]")
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]
[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [47]:
# **Q12.1:** Calculate the dot product of account balance and credit score columns
# The dot product (also called scalar product) of two vectors is a single number obtained by multiplying corresponding elements of the vectors and then summing all the products.
np.dot(banking_data[0:,1],banking_data[0:,2]) 

np.int64(62796500)

In [ ]:
# **Q12.2:** Calculate the cross product of first two rows
# The cross product of two 3D vectors A and B is a vector that is perpendicular to both A and B.
#    manual formula calculation :  A×B=[a2​b3​−a3​b2​, a3​b1​−a1​b3​, a1​b2​−a2​b1​]
row1=banking_data[0,1:4]
row2=banking_data[1,1:4]
print(np.cross(row1,row2))


[    32820     95000 -11482000]


In [ ]:
# **Q12.3:** Calculate the norm (magnitude) of the account balance column
np.linalg.norm(banking_data[0:,1])  


np.float64(33177.96859363153)

In [66]:
# **Q12.4:** Create a 3x3 matrix and calculate its determinant
x=np.random.randint(1,50,(3,3))
print(x)
np.linalg.det(x)


[[ 7 10 24]
 [15 39 20]
 [ 7 13 28]]


np.float64(1152.0000000000014)

In [67]:
# **Q12.5:** Calculate the inverse of the 3x3 matrix
y=np.random.randint(1,50,(3,3))
print(y)
np.linalg.inv(y)

[[39 18 47]
 [11 36 36]
 [ 2 48 46]]


array([[-0.00665927,  0.13207547, -0.09655938],
       [-0.04014058,  0.1572327 , -0.08203848],
       [ 0.04217536, -0.16981132,  0.11154273]])

In [ ]:
### Question 13: String Operations

**Q13.1:** Convert all customer IDs to strings

**Q13.2:** Check if any customer ID contains '100'

**Q13.3:** Convert all customer IDs to uppercase (if they were strings)

**Q13.4:** Count the length of each customer ID string

**Q13.5:** Replace '100' with 'CUST' in customer IDs


In [102]:
import numpy as np
print("[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]")
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]
[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [103]:
# **Q13.1:** Convert all customer IDs to strings
banking_data[:,0].astype(str)


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U21')

In [112]:
# **Q13.2:** Check if any customer ID contains '100'
import numpy as np
cust_id=banking_data[:,0].astype(str)
cust_100 = np.char.find(cust_id,'100') >= 0
any_100=np.any(cust_100)
any_100




np.False_

In [ ]:
# **Q13.3:** Convert all customer IDs to uppercase (if they were strings)


In [117]:
# **Q13.4:** Count the length of each customer ID string
x=banking_data[:,0].astype(str)
str_len=np.char.str_len(x)
str_len

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 2])

In [ ]:
**Q13.5:** Replace '100' with 'CUST' in customer IDs

In [ ]:
### Question 14: Date and Time Operations

**Q14.1:** Convert years active to months

**Q14.2:** Calculate the average years active

**Q14.3:** Find customers who have been active for more than 5 years

**Q14.4:** Calculate the total time all customers have been active (in years)

**Q14.5:** Find the customer with the shortest time active

In [119]:
import numpy as np
print("[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]")
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]
[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [123]:
# **Q14.1:** Convert years active to months
banking_data[0:,4]*12   # 1 year = 12 months 

array([ 24,  96,  12,  72,  36, 120,  12, 144,  60,  48])

In [126]:
# **Q14.2:** Calculate the average years active
np.average(banking_data[0:,4])

np.float64(5.2)

In [128]:
# **Q14.3:** Find customers who have been active for more than 5 years
banking_data[banking_data[0:,4] > 5]

array([[    2, 15000,   650,    42,     8],
       [    4,  8700,   810,    30,     6],
       [    6, 12000,   745,    55,    10],
       [    8, 22000,   860,    70,    12]])

In [130]:
# **Q14.4:** Calculate the total time all customers have been active (in years)
print(banking_data[0:,4].sum())

52


In [134]:
# **Q14.5:** Find the customer with the shortest time active
banking_data[0:,4].min()

np.int64(1)

In [ ]:
### Question 15: Advanced Array Operations

**Q15.1:** Apply a function to calculate 5% interest on all account balances

**Q15.2:** Use `np.where` to categorize customers by balance ranges

**Q15.3:** Use `np.select` to categorize customers by credit score ranges

**Q15.4:** Use `np.piecewise` to apply different interest rates based on balance

**Q15.5:** Use `np.apply_along_axis` to calculate the sum of each row

In [43]:
import numpy as np
print("[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]")
banking_data=np.array([
    [1,5200,720,15,2],
    [2,15000,650,42,8],
    [3,300,500,5,1],
    [4,8700,810,30,6],
    [5,4300,690,18,3],
    [6,12000,745,55,10],
    [7,760,600,8,1],
    [8,22000,860,70,12],
    [9,9000,700,17,5],
    [10,6700,675,22,4]
])
print(banking_data)

[Customer_ID | Account_Balance | Credit_Score | Transaction_Count | Years_active]
[[    1  5200   720    15     2]
 [    2 15000   650    42     8]
 [    3   300   500     5     1]
 [    4  8700   810    30     6]
 [    5  4300   690    18     3]
 [    6 12000   745    55    10]
 [    7   760   600     8     1]
 [    8 22000   860    70    12]
 [    9  9000   700    17     5]
 [   10  6700   675    22     4]]


In [44]:
# **Q15.1:** Apply a function to calculate 5% interest on all account balances
banking_data[0:,1]*0.05

array([ 260.,  750.,   15.,  435.,  215.,  600.,   38., 1100.,  450.,
        335.])

In [45]:
# **Q15.2:** Use `np.where` to categorize customers by balance ranges
# np.where is used because it lets you apply conditions across an entire NumPy array at once (vectorized operations).
# General form : np.where(condition, value_if_true, value_if_false)
balance=banking_data[0:,1]
categories=np.where(balance<3000,"low",
                    np.where(balance<=12000,"medium","high"))
categories

array(['medium', 'high', 'low', 'medium', 'medium', 'medium', 'low',
       'high', 'medium', 'medium'], dtype='<U6')

In [46]:
# **Q15.3:** Use `np.select` to categorize customers by credit score ranges
# np.select is a NumPy function that lets you apply multiple conditions to an array and assign values depending on which condition is True.

balance=banking_data[0:,1]
cond=[balance<3000,balance<=12000,balance<=22000]
ch=["low","med","high"]
cat=np.select(cond,ch,default="very high") # np.select(conditions, choices, default=0)
cat


array(['med', 'high', 'low', 'med', 'med', 'med', 'low', 'high', 'med',
       'med'], dtype='<U9')

In [ ]:
# **Q15.4:** Use `np.piecewise` to apply different interest rates based on balance

balance = banking_data[:,1]
cond = [
    (balance < 3000),
    (balance >= 3000) & (balance <= 12000),
    (balance > 12000)
]
ch = [0.02, 0.05, 0.07]
rates = np.piecewise(balance, cond, ch)   # np.piecewise(x, condlist, funclist)
interest_amount = balance * rates
print("Interest: ", interest_amount)


Interest:  [0 0 0 0 0 0 0 0 0 0]


In [60]:
# **Q15.5:** Use `np.apply_along_axis` to calculate the sum of each row
# np.apply_along_axis lets you take any function (like sum, mean, max, or even your own function) and apply it to 1D slices of a larger array, along a chosen axis.
np.apply_along_axis(np.sum,axis=1,arr=banking_data)   # np.apply_along_axis(func1d, axis, arr)


array([ 5938, 15702,   809,  9550,  5016, 12816,  1376, 22950,  9731,
        7411])

In [ ]:
### Question 16: Array Concatenation and Stacking

**Q16.1:** Concatenate two arrays horizontally using `np.hstack()`

**Q16.2:** Concatenate two arrays vertically using `np.vstack()`

**Q16.3:** Concatenate arrays along a specific axis using `np.concatenate()`

**Q16.4:** Stack arrays depth-wise using `np.dstack()`

**Q16.5:** Create a column stack using `np.column_stack()`


In [ ]:
# **Q16.1:** Concatenate two arrays horizontally using `np.hstack()`
import numpy as np
x=np.random.randint(0,50,(3,3))
print(x)
y=np.random.randint(0,50,(3,3))
print(y)
np.hstack([x,y])   # hstack() : Always using a tuple or list as input  for combining arrays.

[[39 47 18]
 [27 27  0]
 [18 45 22]]
[[ 1 42 17]
 [38  3 14]
 [ 3 21 10]]


array([[39, 47, 18,  1, 42, 17],
       [27, 27,  0, 38,  3, 14],
       [18, 45, 22,  3, 21, 10]], dtype=int32)

In [ ]:
# **Q16.2:** Concatenate two arrays vertically using `np.vstack()`
import numpy as np
x=np.random.randint(0,50,(3,3))
print(x)
y=np.random.randint(0,50,(3,3))
print(y)
np.vstack((x,y))  #  vstack() : Always using a tuple or list as input  for combining arrays.

[[42 49 19]
 [36  7 39]
 [10 42  7]]
[[40  7 45]
 [45 20  3]
 [23 17 23]]


array([[42, 49, 19],
       [36,  7, 39],
       [10, 42,  7],
       [40,  7, 45],
       [45, 20,  3],
       [23, 17, 23]], dtype=int32)

In [ ]:
#**Q16.3:** Concatenate arrays along a specific axis using `np.concatenate()`
import numpy as np
x=np.random.randint(0,50,(3,3))
print(x)
y=np.random.randint(0,50,(3,3))
print(y)
np.concatenate([x,y],axis=1)   #axis=0-->vertical  axis=1-->horizontal

[[32 32  0]
 [ 8 49 12]
 [40  1 31]]
[[17 20 13]
 [31 24 31]
 [12 39 26]]


array([[32, 32,  0, 17, 20, 13],
       [ 8, 49, 12, 31, 24, 31],
       [40,  1, 31, 12, 39, 26]], dtype=int32)

In [20]:
# **Q16.4:** Stack arrays depth-wise using `np.dstack()`
import numpy as np
x=np.random.randint(0,50,(3,3))
print(x)
y=np.random.randint(0,50,(3,3))
print(y)
np.dstack((x,y))

[[22  7 33]
 [37  8 20]
 [10 27  4]]
[[11 18 21]
 [33 44 30]
 [16 30 37]]


array([[[22, 11],
        [ 7, 18],
        [33, 21]],

       [[37, 33],
        [ 8, 44],
        [20, 30]],

       [[10, 16],
        [27, 30],
        [ 4, 37]]], dtype=int32)

In [21]:
# **Q16.5:** Create a column stack using `np.column_stack()`
import numpy as np
x=np.random.randint(0,50,(3,3))
print(x)
y=np.random.randint(0,50,(3,3))
print(y)
np.column_stack((x,y))

[[48 43 34]
 [29 37 40]
 [26 41 13]]
[[48 34 40]
 [16 38 48]
 [ 2 18 39]]


array([[48, 43, 34, 48, 34, 40],
       [29, 37, 40, 16, 38, 48],
       [26, 41, 13,  2, 18, 39]], dtype=int32)

In [ ]:
### Question 17: Array Splitting Operations

**Q17.1:** Split an array into 3 equal parts using `np.split()`

**Q17.2:** Split an array at specific indices using `np.split()`

**Q17.3:** Split an array horizontally using `np.hsplit()`

**Q17.4:** Split an array vertically using `np.vsplit()`

**Q17.5:** Split an array into equal chunks using `np.array_split()`

In [ ]:
#**Q17.1:** Split an array into 3 equal parts using `np.split()`
a=np.random.randint(0,10,(3,3))
print(a)
np.split(a,3)

[[8 2 6]
 [5 2 9]
 [3 6 7]]


[array([[8, 2, 6]], dtype=int32),
 array([[5, 2, 9]], dtype=int32),
 array([[3, 6, 7]], dtype=int32)]

In [30]:
# **Q17.2:** Split an array at specific indices using `np.split()`
a=np.random.randint(0,10,(3,3))
print(a)
np.split(a,[1,3])


[[8 6 7]
 [5 5 5]
 [6 3 0]]


[array([[8, 6, 7]], dtype=int32),
 array([[5, 5, 5],
        [6, 3, 0]], dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [37]:
#**Q17.3:** Split an array horizontally using `np.hsplit()`
a=np.random.randint(0,10,(3,3))
print(a)
np.hsplit(a,[1,3])

[[8 3 5]
 [8 7 6]
 [4 0 8]]


[array([[8],
        [8],
        [4]], dtype=int32),
 array([[3, 5],
        [7, 6],
        [0, 8]], dtype=int32),
 array([], shape=(3, 0), dtype=int32)]

In [38]:
# **Q17.4:** Split an array vertically using `np.vsplit()`
a=np.random.randint(0,10,(3,3))
print(a)
np.vsplit(a,[1,3])

[[2 5 8]
 [7 7 3]
 [4 7 0]]


[array([[2, 5, 8]], dtype=int32),
 array([[7, 7, 3],
        [4, 7, 0]], dtype=int32),
 array([], shape=(0, 3), dtype=int32)]

In [ ]:
# **Q17.5:** Split an array into equal chunks using `np.array_split()`
a=np.arange(0,10)  # creates array from 0 to 9
print(a)  
np.array_split(a,3)

[0 1 2 3 4 5 6 7 8 9]


[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
### Question 18: Array Repetition and Tiling

**Q18.1:** Repeat each element of an array 3 times using `np.repeat()`

**Q18.2:** Repeat an entire array 2 times using `np.tile()`

**Q18.3:** Repeat a 2D array using `np.tile()`

**Q18.4:** Create a pattern using `np.tile()`

**Q18.5:** Repeat elements with different counts using `np.repeat()`

In [47]:
# **Q18.1:** Repeat each element of an array 3 times using `np.repeat()`
a=np.array([1,2,3,4])
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [58]:
# **Q18.2:** Repeat an entire array 2 times using `np.tile()`
a=np.array([1,2,3,4])
np.tile(a,3)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
# **Q18.3:** Repeat a 2D array using `np.tile()`
x=np.array([[1,2],[3,4]])
np.tile(x,reps=3)     # reps meams repeating 

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

In [57]:
# **Q18.4:** Create a pattern using `np.tile()`
x=np.array([[1,2,3],[4,5,6]])
np.tile(x,(2,2))


array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [ ]:
# **Q18.5:** Repeat elements with different counts using `np.repeat()`
x=np.array([1,2,3]) # for 1D array
np.repeat(x,[1,2,3])

array([1, 2, 2, 3, 3, 3])

In [ ]:
# **Q18.5:** Repeat elements with different counts using `np.repeat()`
# for 2D array
x=np.random.randint(1,10,(2,2))
rows=np.repeat(x,[1,3],axis=0)
cols=np.repeat(x,[2,4],axis=1)
print(x)
print()
print(rows)
print("--------------------------------------------------")
print(cols)

[[2 2]
 [3 6]]

[[2 2]
 [3 6]
 [3 6]
 [3 6]]
--------------------------------------------------
[[2 2 2 2 2 2]
 [3 3 6 6 6 6]]


In [ ]:
### Question 19: Array Comparison and Logical Operations

**Q19.1:** Compare two arrays for equality using `np.array_equal()`

**Q19.2:** Check if arrays are close using `np.allclose()`

**Q19.3:** Apply logical AND operation between arrays

**Q19.4:** Apply logical OR operation between arrays

**Q19.5:** Apply logical NOT operation to an array


In [83]:
# **Q19.1:** Compare two arrays for equality using `np.array_equal()`
x=np.array([1,2,4])
print(x)
y=np.array([1,2,4])
print(y)
np.array_equal(x,y)

[1 2 4]
[1 2 4]


True

In [93]:
#**Q19.2:** Check if arrays are close using `np.allclose()`
x=np.array([1.3,2,4])
print(x)
y=np.array([1.4,2.0,4])
print(np.allclose(x,y,atol=0.1))   # if atol is not used then both arrays are not close to each other
print(np.allclose(x,y))

[1.3 2.  4. ]
True
False


In [97]:
# **Q19.3:** Apply logical AND operation between arrays
x=np.array([0,2,4])
y=np.array([1.4,2.0,0])
np.logical_and(x,y)

array([False,  True, False])

In [100]:
# **Q19.4:** Apply logical OR operation between arrays
x=np.array([0,2,4])
y=np.array([0,2.0,0])
np.logical_or(x,y)

array([False,  True,  True])

In [105]:
# **Q19.5:** Apply logical NOT operation to an array
x=np.array([True,True,False])
print(np.logical_not(x,y))

[0. 0. 1.]


In [ ]:
### Question 20: Array Set Operations

**Q20.1:** Find unique elements in an array using `np.unique()`

**Q20.2:** Find the intersection of two arrays using `np.intersect1d()`

**Q20.3:** Find the union of two arrays using `np.union1d()`

**Q20.4:** Find elements in first array but not in second using `np.setdiff1d()`

**Q20.5:** Find the symmetric difference between two arrays using `np.setxor1d()`

In [118]:
# **Q20.1:** Find unique elements in an array using `np.unique()`
x=np.random.randint(0,10,12)
print(x)
print("counts :",np.unique(x))


[7 3 5 2 7 9 5 3 4 2 7 6]
counts : [2 3 4 5 6 7 9]


In [122]:
# **Q20.2:** Find the intersection of two arrays using `np.intersect1d()`
x=np.random.randint(0,10,12)
print(x)
y=np.random.randint(0,10,12)
print(y)
np.intersect1d(x,y)


[9 8 1 0 2 2 2 7 3 0 1 0]
[7 1 0 1 2 6 6 1 8 0 9 9]


array([0, 1, 2, 7, 8, 9], dtype=int32)

In [123]:
# **Q20.3:** Find the union of two arrays using `np.union1d()`
x=np.random.randint(0,10,12)
print(x)
y=np.random.randint(0,10,12)
print(y)
np.union1d(x,y)


[7 4 5 4 1 0 9 6 3 7 1 3]
[2 7 1 6 4 9 8 1 2 7 4 8]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [124]:
# **Q20.4:** Find elements in first array but not in second using `np.setdiff1d()`
x=np.random.randint(0,10,10)
print(x)
y=np.random.randint(0,10,10)
print(y)
np.setdiff1d(x,y)

[5 7 1 2 8 2 8 6 4 6]
[1 1 0 0 2 0 8 8 9 1]


array([4, 5, 6, 7], dtype=int32)

In [126]:
# **Q20.5:** Find the symmetric difference between two arrays using `np.setxor1d()`
x=np.random.randint(0,10,10)
print(x)
y=np.random.randint(0,10,10)
print(y)
np.setxor1d(x,y)


[4 3 9 2 6 4 2 3 0 9]
[9 3 2 2 3 5 4 5 5 8]


array([0, 5, 6, 8], dtype=int32)