In [1]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[6, 0, 3],
       [9, 6, 6],
       [7, 7, 5]], dtype=int32)

In [ ]:
import numpy as np
np.random.rand(30,30).mean()

np.float64(0.49555541324244207)

In [8]:
import numpy as np
data=np.random.randint(0,10,(4,4))
data



array([[0, 0, 4, 8],
       [4, 8, 7, 0],
       [2, 4, 5, 9],
       [4, 9, 9, 9]], dtype=int32)

In [9]:
np.std(data)

np.float64(3.295356581616017)

In [10]:
np.var(data)

np.float64(10.859375)

In [11]:
np.mean(data)

np.float64(5.125)

In [12]:
np.median(data)

np.float64(4.5)

In [14]:
data=np.random.randint(0,100,10)
data

array([38, 54, 82, 34,  7, 85,  9, 66, 70, 81], dtype=int32)

In [15]:
data.min(),data.max()

(np.int32(7), np.int32(85))

In [16]:
range=data.max()-data.min()
range

np.int32(78)

In [20]:
import numpy as np
dt=np.random.randint(0,20,(5,5))
dt

array([[ 7,  3, 17,  2, 14],
       [ 7,  4, 15, 19, 13],
       [12, 13,  3, 17,  7],
       [14, 18, 10,  0,  4],
       [ 4,  5,  9, 16, 16]], dtype=int32)

In [ ]:
print(dt.sum(axis=0)) #vertical sum
print()
print(dt.sum(axis=1))# Horizontal sum

[44 43 54 54 54]

[43 58 52 46 50]


In [28]:
dt


array([[ 7,  3, 17,  2, 14],
       [ 7,  4, 15, 19, 13],
       [12, 13,  3, 17,  7],
       [14, 18, 10,  0,  4],
       [ 4,  5,  9, 16, 16]], dtype=int32)

In [30]:
print(dt.min(axis=0))
print(dt.min(axis=1))

[4 3 3 0 4]
[2 4 3 0 4]


In [31]:
print(dt.max(axis=0))
print(dt.max(axis=1))

[14 18 17 19 16]
[17 19 17 18 16]


In [33]:
dt[0:2,0:2].max()

np.int32(7)

In [35]:
dt[-3:,-2:].max()

np.int32(17)

In [36]:
dt[-3:,-2:].min()

np.int32(0)

In [38]:
data=np.random.randint(0,10,10)
data

array([8, 5, 7, 0, 6, 3, 8, 2, 2, 8], dtype=int32)

In [ ]:
data.min() # min returns the minimum value of an array

np.int32(0)

In [ ]:
data.argmin()  # argmin returns the element minimum value of that index in array

np.int64(3)

In [41]:
data.max()

np.int32(8)

In [42]:
data.argmax()

np.int64(0)

In [43]:
import numpy as np
d=np.random.randint(0,10,(3,3))
d

array([[7, 1, 2],
       [0, 7, 0],
       [5, 3, 8]], dtype=int32)

In [44]:
d.argmax(axis=0)

array([0, 1, 2])

In [45]:
d.argmax(axis=1)

array([0, 1, 2])

In [46]:
d.argmin(axis=0)

array([1, 0, 1])

In [47]:
d.argmin(axis=1)

array([1, 0, 1])

In [ ]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [49]:
## calculate the total sales 
retail_data[:,1].sum()

np.int64(335000)

In [54]:
##"Which store has the highest inventory, and what is its store ID?"
retail_data[:,3].argmax()+1

np.int64(9)

In [ ]:
# sales/customer
# sales/transaction : basket value
# sales/units: basket size

In [11]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])

print(retail_data)

[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [ ]:
f=retail_data[:,1]/retail_data[:,2]
print(f)
x=np.argmax(f)
print(x)

[83.33333333 71.11111111 73.68421053 82.         83.33333333 75.
 81.25       75.         81.81818182 80.48780488]
1


In [ ]:
data=np.random.randint(0,10,3)
data



array([8, 2, 0], dtype=int32)

In [24]:
x=20
data+x

array([28, 22, 20], dtype=int32)

In [25]:
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))
x+y

array([[ 5,  0,  1],
       [13,  8,  9],
       [ 9,  4,  5]], dtype=int32)

In [26]:
x

array([[0],
       [8],
       [4]], dtype=int32)

In [27]:
y

array([[5, 0, 1]], dtype=int32)

In [ ]:
import numpy as np
x=np.random.randint(0,10,(3,1))
y=np.random.randint(0,10,(1,3))


array([[1],
       [8],
       [8]], dtype=int32)

In [4]:
x

array([[1],
       [8],
       [8]], dtype=int32)

In [5]:
y

array([[7, 7, 7]], dtype=int32)

In [6]:
x*y

array([[ 7,  7,  7],
       [56, 56, 56],
       [56, 56, 56]], dtype=int32)