In [2]:
import numpy as np
data=np.random.randint(0,10,(3,3))
data

array([[7, 5, 5],
       [5, 3, 0],
       [2, 2, 4]], dtype=int32)

In [ ]:
# Array Creation operations

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
### Mathematical Functions

In [19]:
import numpy as np
d=np.random.randint(0,10,10)
d

array([7, 6, 6, 6, 3, 7, 4, 1, 9, 3], dtype=int32)

In [23]:
print(np.sin(d))
print(np.cos(d))
print(np.tan(d))

[ 0.6569866  -0.2794155  -0.2794155  -0.2794155   0.14112001  0.6569866
 -0.7568025   0.84147098  0.41211849  0.14112001]
[ 0.75390225  0.96017029  0.96017029  0.96017029 -0.9899925   0.75390225
 -0.65364362  0.54030231 -0.91113026 -0.9899925 ]
[ 0.87144798 -0.29100619 -0.29100619 -0.29100619 -0.14254654  0.87144798
  1.15782128  1.55740772 -0.45231566 -0.14254654]


In [27]:
print(np.arccos(d))
print()
print(np.arcsin(d))
print()
print(np.arctan(d))

[nan nan nan nan nan nan nan  0. nan nan]

[       nan        nan        nan        nan        nan        nan
        nan 1.57079633        nan        nan]

[1.42889927 1.40564765 1.40564765 1.40564765 1.24904577 1.42889927
 1.32581766 0.78539816 1.46013911 1.24904577]


C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_24416\437330748.py:1: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(d))
C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_24416\437330748.py:3: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(d))


In [32]:
np.log(d)

array([1.94591015, 1.79175947, 1.79175947, 1.79175947, 1.09861229,
       1.94591015, 1.38629436, 0.        , 2.19722458, 1.09861229])

In [33]:
np.log2(d)

array([2.80735492, 2.5849625 , 2.5849625 , 2.5849625 , 1.5849625 ,
       2.80735492, 2.        , 0.        , 3.169925  , 1.5849625 ])

In [34]:
np.log10(d)

array([0.84509804, 0.77815125, 0.77815125, 0.77815125, 0.47712125,
       0.84509804, 0.60205999, 0.        , 0.95424251, 0.47712125])

In [35]:
np.e

2.718281828459045

In [36]:
np.log(np.sqrt(2.718281828459045))

np.float64(0.5)

In [38]:
import math
np.log(math.pow(2.718281828459045,0.2867))

np.float64(0.2867)

In [39]:
x=np.random.randint(0,10,(3,3))
y=np.random.randint(0,10,(3,3))

In [40]:
x

array([[9, 8, 6],
       [6, 9, 4],
       [6, 4, 8]], dtype=int32)

In [41]:
y

array([[0, 2, 5],
       [5, 7, 8],
       [6, 6, 7]], dtype=int32)

In [42]:
x+y

array([[ 9, 10, 11],
       [11, 16, 12],
       [12, 10, 15]], dtype=int32)

In [43]:
np.add(x,y)

array([[ 9, 10, 11],
       [11, 16, 12],
       [12, 10, 15]], dtype=int32)

In [44]:
np.subtract(x,y)

array([[ 9,  6,  1],
       [ 1,  2, -4],
       [ 0, -2,  1]], dtype=int32)

In [45]:
np.multiply(x,y)

array([[ 0, 16, 30],
       [30, 63, 32],
       [36, 24, 56]], dtype=int32)

In [46]:
np.divide(x,y)

C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_24416\430945158.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(x,y)


array([[       inf, 4.        , 1.2       ],
       [1.2       , 1.28571429, 0.5       ],
       [1.        , 0.66666667, 1.14285714]])

In [47]:
np.floor_divide(x,y)

C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_24416\2566742545.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.floor_divide(x,y)


array([[0, 4, 1],
       [1, 1, 0],
       [1, 0, 1]], dtype=int32)

In [50]:
d1=np.random.randint(0,10,10)/5
print(d1)
np.ceil(d1)

[1.  1.6 0.8 0.8 1.4 1.4 1.4 0.2 0.2 1.2]


array([1., 2., 1., 1., 2., 2., 2., 1., 1., 2.])

In [ ]:
# Mathematical:
#  Arithmetic
#  exponential, log
#  trigonometrics
#  rounding

In [51]:
import numpy as np
d=np.random.randint(0,10,10)
d

array([6, 4, 7, 6, 5, 4, 3, 0, 7, 8], dtype=int32)

In [52]:
d[d>5]

array([6, 7, 6, 7, 8], dtype=int32)

In [54]:
marks=np.random.randint(0,100,20)
marks

array([54, 19, 43, 38, 87, 97, 16, 68, 46, 93, 28, 26, 11, 73, 43, 46, 64,
       47,  2, 84], dtype=int32)

In [55]:
marks[marks>50]

array([54, 87, 97, 68, 93, 73, 64, 84], dtype=int32)

In [56]:
marks[marks>np.mean(marks)]

array([54, 87, 97, 68, 93, 73, 64, 84], dtype=int32)

In [59]:
marks[marks<np.mean(marks)]

array([19, 43, 38, 16, 46, 28, 26, 11, 43, 46, 47,  2], dtype=int32)

In [60]:
# Array manipulation


In [62]:
z=np.random.randint(0,20,(3,3))
z

array([[14, 19, 11],
       [ 0, 16, 17],
       [ 6, 10,  1]], dtype=int32)

In [ ]:
np.ravel(z)    # ravel() method is used for falttening the array elements

array([14, 19, 11,  0, 16, 17,  6, 10,  1], dtype=int32)

In [65]:
z.T   # T is a transpose of a array it converts rows to columns and columns to rows

array([[14,  0,  6],
       [19, 16, 10],
       [11, 17,  1]], dtype=int32)

In [70]:
z=np.random.randint(0,20,(20))
z.reshape(2,10)

array([[15, 12, 16,  9, 18, 14,  9,  8,  5,  3],
       [16,  6,  7,  0, 12, 14, 14, 18,  3,  5]], dtype=int32)

In [71]:
z.reshape(4,5)

array([[15, 12, 16,  9, 18],
       [14,  9,  8,  5,  3],
       [16,  6,  7,  0, 12],
       [14, 14, 18,  3,  5]], dtype=int32)

In [72]:
z.reshape(5,4)

array([[15, 12, 16,  9],
       [18, 14,  9,  8],
       [ 5,  3, 16,  6],
       [ 7,  0, 12, 14],
       [14, 18,  3,  5]], dtype=int32)

In [73]:
z.reshape(10,2)

array([[15, 12],
       [16,  9],
       [18, 14],
       [ 9,  8],
       [ 5,  3],
       [16,  6],
       [ 7,  0],
       [12, 14],
       [14, 18],
       [ 3,  5]], dtype=int32)

In [76]:
d1=np.random.randint(0,20,(3,3))
d2=np.random.randint(0,20,(3,3))

In [77]:
d1

array([[ 6,  9,  2],
       [19,  5,  2],
       [ 8, 13,  6]], dtype=int32)

In [78]:
d2

array([[11,  3, 19],
       [14, 19, 16],
       [16, 14, 19]], dtype=int32)

In [79]:
np.hstack([d1,d2])

array([[ 6,  9,  2, 11,  3, 19],
       [19,  5,  2, 14, 19, 16],
       [ 8, 13,  6, 16, 14, 19]], dtype=int32)

In [80]:
np.vstack([d1,d2])

array([[ 6,  9,  2],
       [19,  5,  2],
       [ 8, 13,  6],
       [11,  3, 19],
       [14, 19, 16],
       [16, 14, 19]], dtype=int32)

In [81]:
data=np.random.randint(0,20,10)
data

array([ 3,  0,  6, 16,  7,  7,  9,  6,  7, 11], dtype=int32)

In [82]:
np.split(data,5)

[array([3, 0], dtype=int32),
 array([ 6, 16], dtype=int32),
 array([7, 7], dtype=int32),
 array([9, 6], dtype=int32),
 array([ 7, 11], dtype=int32)]

In [83]:
np.split(data,2)

[array([ 3,  0,  6, 16,  7], dtype=int32),
 array([ 7,  9,  6,  7, 11], dtype=int32)]

In [84]:
np.split(data,4)

ValueError: array split does not result in an equal division

In [87]:
matrix=np.array([[1,2,3,4] ,[5,6,7,8]])
matrix

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [88]:
np.hsplit(matrix,2)

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [92]:
np.hsplit(matrix,4)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [94]:
matrix1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

In [95]:
matrix1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [97]:
np.vsplit(matrix1,2)

[array([[1, 2, 3, 4],
        [5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])]

In [98]:
np.vsplit(matrix1,4)

[array([[1, 2, 3, 4]]),
 array([[5, 6, 7, 8]]),
 array([[ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [104]:
np.vsplit(matrix1,[1,3])

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]

In [106]:
np.vsplit(matrix1,[1,3])

[array([[1, 2, 3, 4]]),
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16]])]