In [8]:
import numpy as np
data=np.random.randint(0,10,(5,5))
data

array([[3, 9, 1, 8, 4],
       [3, 2, 6, 4, 5],
       [9, 6, 4, 1, 7],
       [6, 3, 3, 5, 4],
       [1, 5, 7, 4, 0]], dtype=int32)

In [9]:
type(data)

numpy.ndarray

In [10]:
type(np.array([1,2,3]))

numpy.ndarray

In [11]:
data[0,0]

np.int32(3)

In [12]:
data

array([[3, 9, 1, 8, 4],
       [3, 2, 6, 4, 5],
       [9, 6, 4, 1, 7],
       [6, 3, 3, 5, 4],
       [1, 5, 7, 4, 0]], dtype=int32)

In [13]:
import numpy as np
d=np.random.randint(0,100,(5,5))
d

array([[23, 79, 73, 87, 48],
       [13,  8, 31,  5, 17],
       [30, 54, 72, 77, 28],
       [87, 51, 57, 92, 44],
       [14, 11, 66, 95, 19]], dtype=int32)

In [14]:
 d[0,0]

np.int32(23)

In [ ]:
print(d[-3:-1,-3:-1])  

[[72 77]
 [57 92]]


In [17]:
d[-2:-1,-2:-1]

array([[92]], dtype=int32)

In [21]:
x=[1,3,2]
print(type(x))
y=np.array([1,3,2])
print(type(y))

<class 'list'>
<class 'numpy.ndarray'>


In [23]:
#differences
# 1. If we perform operations(like +,-,/,*) on list  it throws error showing cannot perform operations on list where as in numpy array it is designed to perfrom all element arithmentic operations
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [24]:
y/2

array([0.5, 1.5, 1. ])

In [ ]:
# 2. In list float type and int type elements remains same  where as in numpy array if few elements are int,float,str type then it converts the priority of datatype for all elements in a numpy array because it numpy elements must contain same data type
# priority order is str > float > int 
# list is a collection of heterogeneous elements
# numpy is a collection of same type elements
x=[1,2,3,6.0,"data"]
y=np.array([1,2,3,5.0,"data"])
print(x)
print(y)

[1, 2, 3, 6.0, 'data']
['1' '2' '3' '5.0' 'data']


In [ ]:
# 3.performance wise numpy is better than list because Much faster for large numerical data and  Takes less Memmory where as list is Slower for large computations and More memory

In [ ]:
#Random family functions

In [1]:
import numpy as np
np.random.randint(0,100,(5,10))

array([[77, 76,  3, 25, 45, 31, 67,  5, 47, 92],
       [25, 35, 89, 34, 25, 33, 41, 73, 83, 34],
       [ 1, 27, 89,  9, 40, 93, 47, 10, 51, 15],
       [25, 87, 93, 84, 69, 63, 44, 44, 44, 25],
       [45, 13, 67, 93, 19, 55,  5, 56, 12, 54]], dtype=int32)

In [ ]:
np.random.rand(3,3)  # rand will give numeric values ranging form 0 to 1

array([[0.54291466, 0.90520764, 0.66119092],
       [0.25432481, 0.35111582, 0.27845391],
       [0.54279499, 0.33015373, 0.03516078]])

In [3]:
np.random.rand(100)

array([0.57284117, 0.06762774, 0.70148756, 0.66737805, 0.30279624,
       0.12167779, 0.86974589, 0.23846375, 0.63767035, 0.63776219,
       0.67701865, 0.48993402, 0.15341398, 0.46679731, 0.04499935,
       0.86027091, 0.99752502, 0.56892094, 0.17266969, 0.00129775,
       0.31514844, 0.61812572, 0.94197594, 0.82394556, 0.86933684,
       0.2324305 , 0.69557781, 0.80749592, 0.60294898, 0.01545797,
       0.8401198 , 0.28693566, 0.13139597, 0.41909058, 0.34667723,
       0.34920208, 0.00120389, 0.62947208, 0.43261115, 0.25360801,
       0.3202631 , 0.28974499, 0.54114169, 0.49415406, 0.21907012,
       0.11428799, 0.44841058, 0.06415589, 0.23285866, 0.58193744,
       0.3942718 , 0.11997555, 0.5166176 , 0.01706216, 0.57209484,
       0.22946199, 0.15094236, 0.51264981, 0.99962925, 0.38618444,
       0.23252623, 0.72085192, 0.68435721, 0.98815056, 0.68495817,
       0.83263405, 0.10443957, 0.58042367, 0.38757087, 0.09238135,
       0.3066737 , 0.38308238, 0.01119431, 0.98350214, 0.05994

In [ ]:
import numpy as np
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())    # scaling the data , this is also known as normalization of data and it is also known as min-max scaling 

array([0.        , 0.33333333, 0.66666667, 1.        ])