In [1]:
import numpy as np
data=np.random.randint(0,20,10)
data

array([ 4,  4,  8,  0,  5, 17, 14,  1, 17, 12], dtype=int32)

In [2]:
np.quantile(data,0.25)

np.float64(4.0)

In [3]:
np.quantile(data,0.5)

np.float64(6.5)

In [6]:
np.quantile(data,0.75)

np.float64(13.5)

In [5]:
np.quantile(data,1)

np.int32(17)

In [9]:
d=np.random.randint(0,20,(3,3))
d

array([[ 9,  0,  5],
       [11, 14,  9],
       [16, 17,  9]], dtype=int32)

In [10]:
np.corrcoef(d)

array([[ 1.        , -0.64622084, -0.17806844],
       [-0.64622084,  1.        ,  0.8660254 ],
       [-0.17806844,  0.8660254 ,  1.        ]])

In [11]:
import numpy as np
np.loadtxt("E:\DATA SCIENCE\Python\Sample.csv",delimiter=',',skiprows=1)

<>:2: SyntaxWarning: invalid escape sequence '\D'
<>:2: SyntaxWarning: invalid escape sequence '\D'
C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_25808\2087543841.py:2: SyntaxWarning: invalid escape sequence '\D'
  np.loadtxt("E:\DATA SCIENCE\Python\Sample.csv",delimiter=',',skiprows=1)


array([[ 21.,  54.,  40.],
       [ 96.,  46.,  83.],
       [ 75.,  86.,  76.],
       [ 17.,  81.,  83.],
       [100.,  78.,  28.],
       [ 72.,  41., 100.]])

In [13]:
data=np.random.randint(0,100,(10,10))
data

array([[17, 41, 98, 14, 15, 76, 93, 16, 33, 71],
       [15, 11, 28,  8, 92, 63, 79, 37, 71, 45],
       [ 4, 74, 16,  1, 52, 42, 82, 46, 22, 56],
       [66, 61, 66, 22, 43,  8, 90, 36, 91, 52],
       [89, 73, 48, 62, 24, 28, 11,  6, 13, 81],
       [67, 11, 56, 18, 23, 14, 27, 66, 12, 16],
       [12, 86, 69, 59, 44,  8, 14, 44,  7, 55],
       [39, 47, 31, 48, 85, 18, 73, 52, 29, 76],
       [93, 74, 86, 12, 54, 62, 10, 28, 78, 36],
       [90, 67,  8, 54, 34, 87, 15, 19, 56, 84]], dtype=int32)

In [15]:
x=np.save("array.npy",data)
x

In [ ]:
import numpy as np
arr=np.random.randint(0,100,(10,5))
np.save("array.npy",arr)  #save file first
load=np.load("array.npy",) # then load
print("Loaded from npy",load)

Loaded from npy [[32 27 78 56 81]
 [98 76 19 76 90]
 [12  9 25 12 68]
 [29 83 10 92 68]
 [34 96 13 90 80]
 [20 29 26 20 25]
 [ 1  4 22 26 18]
 [72  3  1 21 95]
 [23 70 97 54 66]
 [19 79 75 33 23]]


In [20]:
arr=np.fromstring("1 2 3 4 5",sep=' ',dtype=int)
arr

array([1, 2, 3, 4, 5])

In [30]:
arr=np.fromstring("1.1,2.2,3.3,4.4,5.5",sep=',')
print(arr)

[1.1 2.2 3.3 4.4 5.5]


In [31]:
arr=np.fromstring("1.1,2.2,3.3,4.4,5.5",sep=',',count=3)
print(arr)

[1.1 2.2 3.3]


In [35]:
txt=open("E:\DATA SCIENCE\Python\samp.txt")
print(txt.read())

Data Science
Machine Learning
Gen AI
Python
SQL


<>:1: SyntaxWarning: invalid escape sequence '\D'
<>:1: SyntaxWarning: invalid escape sequence '\D'
C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_25808\416439599.py:1: SyntaxWarning: invalid escape sequence '\D'
  txt=open("E:\DATA SCIENCE\Python\samp.txt")


In [49]:
txt.seek(1)
print(txt.read().splitlines())

['ata Science', 'Machine Learning', 'Gen AI', 'Python', 'SQL']


In [ ]:
| Mode  | Meaning                   | Can Read? | Can Write? | File Created if Missing? |
|-------|---------------------------|-----------|------------|--------------------------|
| `r`   | Read text                 | ✅        | ❌         | ❌                       |
| `w`   | Write text (overwrite)    | ❌        | ✅         | ✅                       |
| `a`   | Append text               | ❌        | ✅         | ✅                       |
| `r+`  | Read + write              | ✅        | ✅         | ❌                       |
| `rb`  | Read binary               | ✅        | ❌         | ❌                       |
| `wb`  | Write binary              | ❌        | ✅         | ✅                       |


In [4]:
with open("first.txt",'w') as file:
    file.write("rakesh")

In [3]:
with open("first.txt",'r') as f:
    content=f.read()
    print(content)

rakesh


In [22]:
with open("first.txt",'a') as file:
    file.write("data\n")
    file.write("science\n")
    file.write("ML\n")

In [9]:
with open("first.txt",'r') as f:
    content=f.read()
    print(content)

rakeshdatascienceMLdata
science
ML



In [23]:
with open("first.txt",'r+') as f:
    txt=f.read()
    f.seek(1)
    f.write("updated content"+txt)

In [24]:
with open("first.txt",'r') as f:
    print(f.read())

dupdated contentdata
science
ML



In [34]:
import PyPDF2
# Open the PDF in read-binary mode
with open("E:\DATA SCIENCE\Python\Design and Implementation of Sensor-IntegratedGesture-Controlled Smart Water Tap.pdf",'rb') as f:
    reader=PyPDF2.PdfReader(f)
    print("number of pages",len(reader.pages))
# Extracting  pages from pdf
    for i in range(0,len(reader.pages)):
        page=reader.pages[i]
        txt=page.extract_text()
        print(f"pages {i} :",txt)
        




<>:3: SyntaxWarning: invalid escape sequence '\D'
<>:3: SyntaxWarning: invalid escape sequence '\D'
C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_10816\4234107093.py:3: SyntaxWarning: invalid escape sequence '\D'
  with open("E:\DATA SCIENCE\Python\Design and Implementation of Sensor-IntegratedGesture-Controlled Smart Water Tap.pdf",'rb') as f:


number of pages 7
pages 0 :  
 
 
 
Design and Implementation of Sensor -Integrated 
Gesture -Controlled  Smart Water Tap  
 
Chidananda H1, Hamsini P2, Geetha Sri Jaya CH3, Sahana D4 and Galibhe Neeraja5 
1-5Ballari Institute of Technology and Management Ballari, Karnataka, India  
Email: chidably999@bitm.edu.in, hamsinireddy481@gmail.com, geethasrijayach@gmail.com, dsahana0321@gm ail.com, 
galibheneeraja1611@gmail.com  
  
 
Abstract — This work introduces an innovative system that interfaces Arduino with an ultrasonic 
sensor to create an intelligent water tap. The system utilizes the proximity in formation gathered 
by the ultrasonic sensor to dynamically adjust the water flow based on the distance between the 
hand and the water tap. Additionally, the system incorporates an automatic water filling feature 
when a container is placed, in the range of ultrasonic sensor. The water flow is controlled through 
an AC dimmer module and a water pump, ensuring variable flow rates and effic

In [35]:
import json

# Python dictionary
data = {
    "name": "John Doe",
    "age": 30,
    "skills": ["Python", "Data Engineering", "AWS"]
}

# Write to JSON file
with open("data.json", "w") as file:
    json.dump(data, file, indent=4)

print("JSON file created successfully!")

JSON file created successfully!


In [36]:
with open("data.json", "r") as file:
    loaded_data = json.load(file)

print("Loaded JSON content:", loaded_data)

Loaded JSON content: {'name': 'John Doe', 'age': 30, 'skills': ['Python', 'Data Engineering', 'AWS']}


In [2]:
import cv2

# Read an image
img = cv2.imread("E:\DATA SCIENCE\Python\img.png")

# Show the image
cv2.imshow("Image Window", img)

# Wait for a key press (0 means wait indefinitely)
cv2.waitKey(0)

# Close all OpenCV windows
cv2.destroyAllWindows()


<>:4: SyntaxWarning: invalid escape sequence '\D'
<>:4: SyntaxWarning: invalid escape sequence '\D'
C:\Users\P VENKATA RAKESH\AppData\Local\Temp\ipykernel_11548\1306931120.py:4: SyntaxWarning: invalid escape sequence '\D'
  img = cv2.imread("E:\DATA SCIENCE\Python\img.png")


In [3]:
type(img)

numpy.ndarray

In [4]:
img.shape

(758, 760, 3)

In [5]:
img[0,0]

array([49, 49, 49], dtype=uint8)

In [ ]:
import cv2
img = cv2.imread("E:\DATA SCIENCE\Python\img.png")
cv2.imshow("MY IMAGE",img)